version: '3.1'

services:
  tests:
    container_name: tests
    image: queue-dev
    build: 
      context: .
      dockerfile: Dockerfile-php-${PHP_VERSION:-8.3}
    volumes:
      - ./:/usr/local/src
    depends_on:
      - redis
      - swoole
      - workerman

  swoole:
    container_name: swoole
    image: queue-dev
    command: php /usr/src/code/tests/Queue/servers/Swoole/worker.php
    volumes:
      - ./:/usr/src/code
    depends_on:
      - redis

  workerman:
    container_name: workerman
    image: queue-dev
    command: php /usr/src/code/tests/Queue/servers/Workerman/worker.php start
    volumes:
      - ./:/usr/src/code
    depends_on:
      - redis

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"